set nocompatible
filetype off

" --- Setup plugins ---
source ~/.vim/plug.vimrc

" --- Basic Configurations ---
source ~/.vim/basic.vimrc

" --- Statusline Setup
source ~/.vim/statusline.vimrc

" --- Misc Plugin Configuration
source ~/.vim/plugins.vimrc

" --- Setup bindings into tmux
source ~/.vim/tmux.vimrc
